site_name: Mind the Gap
site_author: Paul McKillop

repo_url: https://github.com/pgmckillop/mind_the_gap
site_description: Content added and modified in the new T-Level Qualification Digital Software Development
site_url: https://mtg.paulmckillop.com/

plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: true

  # Consolidated Pymdownx Extensions
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.expand
    - navigation.tracking
    - navigation.subnavigation.indent
    - toc.integrate
    - search.highlight
    - search.share
  palette:
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple

    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep purple

nav:
  - Home: index.md
  - The Gap: ca000-the-gap/the-gap.md

  - 1 PRO:
      - Introduction: ca101-problem-solving/home-01.md
      - 1.1 Computational Thinking:
          - 1.1.1 Computational Thinking: ca101-problem-solving/1-1-computational-thinking/1-1-1-computational-thinking.md
          - 1.1.6 Decomposition: ca101-problem-solving/1-1-computational-thinking/1-1-6-decomposition.md
          - 1.1.9 Information Flow Diagrams: ca101-problem-solving/1-1-computational-thinking/1-1-9-info-flow-diagrams.md
      - 1.2 Algorithmic Design:
          - 1.2.0 Algorithmic Design: ca101-problem-solving/1-2-algorithmic-design/1-2-0-algorithmic-design.md
      - 1.3 Strategies:
          - 1.3.3 Cause Analysis: ca101-problem-solving/1-3-strategies/1-3-3-cause-analysis.md
          - 1.3.4.1 Five Whys: ca101-problem-solving/1-3-strategies/1-3-4-1-five-whys.md
          - 1.3.4.2 Failure Mode Effects Analysis: ca101-problem-solving/1-3-strategies/1-3-4-2-failure-mode-effects-analysis.md
          - 1.3.4.3 Event Tree Analysis: ca101-problem-solving/1-3-strategies/1-3-4-3-event-tree-analysis.md
          - 1.3.4.4 Actions after RCA: ca101-problem-solving/1-3-strategies/1-3-4-4-actions-after-rca.md
          - 1.3.5 High Level Problem Solving: ca101-problem-solving/1-3-strategies/1-3-5-high-level-problem-solving.md
          - 1.3.6.1 Interrelationships: ca101-problem-solving/1-3-strategies/1-3-6-1-interrelationships.md
          - 1.3.6.2 Interrelationships Examples: ca101-problem-solving/1-3-strategies/1-3-6-2-interrelationships-examples.md

  - 2 ITP:
      - Introduction: ca102-intro-to-programming/home-02.md
      - 2.1 Data Types:
          - 2.1.1 Standard Types: ca102-intro-to-programming/2-01-data-types/2-1-1-standard-types.md
      - 2.2 Variables and Constants:
          - 2.2.2 Constants: ca102-intro-to-programming/2-02-variables-constants/2-2-2-constants.md
          - 2.2.3 Type Conversion: ca102-intro-to-programming/2-02-variables-constants/2-2-3-type-conversion.md
          - 2.2.6 Scope: ca102-intro-to-programming/2-02-variables-constants/2-2-6-scope.md
          - 2.2.7 Declare and Use: ca102-intro-to-programming/2-02-variables-constants/2-2-7-declare-and-use.md
      - 2.3 Data Structures:
          - 2.3.0 Code Structures: ca102-intro-to-programming/2-03-data-structures/2-3-0-code-structures.md
      - 2.4 Operators:
          - 2.4.0 Operators: ca102-intro-to-programming/2-04-operators/2-4-0-operators.md
      - 2.5 Input and Output:
          - 2.5.1 Implement IO: ca102-intro-to-programming/2-05-input-output/2-5-1-implement-io.md
          - 2.5.2 File Operations: ca102-intro-to-programming/2-05-input-output/2-5-2-file-operations.md
      - 2.6 Actions:
          - 2.6.0 Actions: ca102-intro-to-programming/2-06-actions/2-6-0-actions.md
          - 2.6.2 Match Case: ca102-intro-to-programming/2-06-actions/2-6-2-match-case.md
          - 2.6.5 Benefits and Drawbacks of Loops: ca102-intro-to-programming/2-06-actions/2-6-5-benefits-drawbacks-loops.md
      - 2.7 Functions and Procedures:
          - 2.7.1.2 Functions and Procedures: ca102-intro-to-programming/2-07-functions-procedures/2-7-1-2-functions-procedures.md
          - 2.7.3 Origins of Code: ca102-intro-to-programming/2-07-functions-procedures/2-7-3-origins-of-code.md
          - 2.7.4 Benefits and Drawbacks of Prewritten: ca102-intro-to-programming/2-07-functions-procedures/2-7-4-benefits-drawbacks-prewritten.md
      - 2.9 Design Considerations and Practices:
          - 2.9.1 Order of Code: ca102-intro-to-programming/2-09-design-considerations-practices/2-9-1-order-of-code.md
          - 2.9.5 Conventions: ca102-intro-to-programming/2-09-design-considerations-practices/2-9-5-conventions.md
          - 2.9.7.1 Judgements Suitability: ca102-intro-to-programming/2-09-design-considerations-practices/2-9-7-1-judgements-suitablility.md
          - 2.9.7.2 Examples: ca102-intro-to-programming/2-09-design-considerations-practices/2-9-7-2-examples.md
      - 2.10 Robust Code:
          - 2.10.0 Robust Code: ca102-intro-to-programming/2-10-robust-code/2-10-0-robust-code.md
      - 2.11 Common Algorithms:
          - 2.11.4 Metrics Compare Algorithms: ca102-intro-to-programming/2-11-common-algortithms/2-11-4-metrics-compare-algorithms.md
      - 2.12 Testing:
          - 2.12.2.1 Testing Methods: ca102-intro-to-programming/2-12-testing/2-12-2-1-testing-methods.md
          - 2.12.3.1 Automation Methods: ca102-intro-to-programming/2-12-testing/2-12-3-1-automation-methods.md
          - 2.12.4 Test Data Plan: ca102-intro-to-programming/2-12-testing/2-12-4-test-data-plan.md

  - 3 EMI:
      - Introduction: ca103-emerging-issues/home-03.md

  - 4 LAR:
      - Introduction: ca104-legislation-regulation/home-04.md

  - 5 BUC:
      - Introduction: ca105-business-context/home-05.md

  - 6 DAT:
      - Introduction: ca106-data/home-06.md
      - 6.1 Data, Information, and Knowledge:
          - 6.1.1 Data, Information, and Knowledge: ca106-data/6-01-data-information-knowledge/6-1-1-data-information-knowledge.md
          - 6.1.2 Sources for Generation: ca106-data/6-01-data-information-knowledge/6-1-2-sources-for-generation.md
          - 6.1.3 Ethics and Metrics: ca106-data/6-01-data-information-knowledge/6-1-3-Ethics-and-metrics.md
          - 6.1.4 Organisation Usage: ca106-data/6-01-data-information-knowledge/6-1-4-organisation-usage.md
          - 6.1.5 Interrelationships: ca106-data/6-01-data-information-knowledge/6-1-5-interrelationships.md
      - 6.2 Methods of Transforming Data:
          - 6.2.1 Transforming Data: ca106-data/6-02-methods-transform-data/6-2-1-transforming-data.md
      - 6.3 Data Taxonomy:
          - 6.3.1 Quantitative and Qualitative: ca106-data/6-03-data-taxonomy/6-3-1-quantitative-qualitative.md
          - 6.3.2 Structured Data: ca106-data/6-03-data-taxonomy/6-3-2-structured-data.md
          - 6.3.3 Unstructured Data: ca106-data/6-03-data-taxonomy/6-3-3-unstructured-data.md
          - 6.3.4 Represent Quantitative: ca106-data/6-03-data-taxonomy/6-3-4-represent-quantitative.md

  - 7 DEN:
      - Introduction: ca107-digital-environments/home-07.md

  - 8 SEC:
      - Introduction: ca108-security/home-08.md
